### ISSUE TITLE
[BUG] Incorrect metadata recognization

### ISSUE THREAD

**Issue by ShiiDD** [Future-Scholars/paperlib#303]
**Describe the bug**
arxiv.org/pdf/2302.03495.pdf
The recognized metadata is about another paper, "TestRank: Bringing Order into Unlabeled Test Instances for Deep Learning Tasks". 

**To Reproduce**
No matter use "Add to Paperlib" on Google Scholar or click the Paperlib extension button, the metadata is always wrong. Even when uploading the downloaded pdf file into the app, it cannot correctly recognize the metadata.

**System (please complete the following information):**
 - OS: MacOS and Win11
 - Paperlib Version 2.2.5

**Comment by GeoffreyChen777** [comment]
HI, thanks for reporting this.

The reason is that this paper used a wrong DOI in their paper.

![image](https://github.com/Future-Scholars/paperlib/assets/14183213/cbfbca27-a53c-4710-bfd9-8a99e75d8dd6)


If a paper has a valid DOI, paperlib will use it to scrape the metadata in priority.

To solve this issue, you can manually input the arxiv id of this paper in the EditView, and try rescrape. =

**Comment by ShiiDD** [comment]
Hi, thanks for the quick reply.
Given that papers on the arxiv are not peer-reviewed, many may not have a valid DOI. This is a common problem, although maybe not that common. Would you consider providing an automatic way in the future version?

**Comment by GeoffreyChen777** [comment]
Usually, an under-reviewing doesn't contain any DOI in their paper.

It's a little bit hard to process issues like this. The reason is that it is difficult to tell whether the DOI written by the author in the paper is random or real.

Usually, if the author writes a wrong DOI, such as 123.456/xxx, the metadata scraper cannot retrieve a valid publication, paperlib will use other information such as title, arxiv id etc. for scraping. But here this paper is a very corner case as the authors used a random but VALID DOI.

**Comment by ShiiDD** [comment]
How about adding a validation step that compares the scraped metadata title to the title from other information (such as the actual title or arxiv id title)?

**Comment by GeoffreyChen777** [comment]
Maybe it's doable, but should be a very complicated system.

The reason is that:
1. There are a lot of papers that changed their metadata before and after publication. Thus we cannot simply compare metadata from different sources.

2. The program doesn't know which metadata is correct. Maybe for some papers, the title from DOI metadata is correct, but the arxiv title is just a draft title.

3. We cannot scrape the metadata from multiple sources and vote. The reason is that many metadata API is very slow. To speed up the scraping process, paperlib has an early-stop scheme. Once an API gives us a valid and full metadata of a paper, the scraping will stop here and send it to the user.

Currently, there is a metadata merging principle in paperlib. The priority of DOI is very high. Because in most cases, DOI gives us correct metadata. That is the most efficient and accurate way for paperlib for now.

https://github.com/Future-Scholars/paperlib/blob/8b19e83f3880e80e8b5a0eb99ac72ca461777323/app/repositories/scraper-repository/scraper-repository.ts#L63C5-L63C5

**Comment by ShiiDD** [comment]
Thanks for your detailed explanations. Completely understood.

How about a vote strategy for authors? The title may vary between editions, but the author, especially the first author, should be stable. Considering the possibility of author change, a threshold of 3 out of 5 authors being the same might be helpful. Also, the first author can have a higher weight. 

I understand it will still be a complicated process. Even a simple decision tree for real cases needs a lot of adjustment. Manually revising metadata for a few papers is not a big problem. Thanks again for your work. I really like Paperlib because it recognizes conferences correctly and has a modern aesthetic ui design. 👍

**Comment by GeoffreyChen777** [comment]
Thanks for your like.
