### ISSUE TITLE
[BUG] MS Word add-in cannot connect to paperlib when system proxy is on

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#392]
**Describe the bug**

When system proxy is on, add-in cannot connect to paperlib.

**Screenshots or Log**

![image](https://github.com/Future-Scholars/paperlib/assets/79003314/42d0c253-beac-464c-918c-218ab0450242)

**System (please complete the following information):**
 - OS: Tested on Windows 11 and MacOS (Web Office)
 - Paperlib Version 2.2.9

**Comment by GeoffreyChen777** [comment]
The reason is that, 

In Paperlib, we create a local socket server and listen `localhost:21993` for communication between the Paperlib APP and the Word add-in.

However, Word add-in must use a domain to communicate to a server. And localhost is invalid.

Thus, we use the domain `localhost2.paperlib.app` and let its DNS record be `127.0.0.1` for a workaround.

To solve this issue, please make sure that `localhost2.paperlib.app` is not in your proxy rules.

In some versions of paperlib, the domain is `localhost.paperlib.app`. I would you suggest check for this also.

**Comment by fkcptlst** [comment]
Thanks! Now I get it. Closing issue as completed.

**Comment by Lixiao-bai** [comment]
> Thanks! Now I get it. Closing issue as completed.

hi, I am having the same issues as you had, using Clash Verge Rev adn I tried change the config.yaml but still not work, only work when I turn off the TUN mode And System proxy mode, cloud you help me with this?

**Comment by fkcptlst** [comment]
> > Thanks! Now I get it. Closing issue as completed.
> 
> hi, I am having the same issues as you had, using Clash Verge Rev adn I tried change the config.yaml but still not work, only work when I turn off the TUN mode And System proxy mode, cloud you help me with this?

I’m not sure. I simply disabled the proxy and then it worked.

**Comment by GeoffreyChen777** [comment]
@Lixiao-bai please modify your proxy rule to make sure that `localhost2.paperlib.app` is using the DIRECT rule.

<img width="499" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/e87064e6-2ef9-4b05-8f66-40cdf5c3a9b3">

`- DOMAIN,localhost2.paperlib.app,DIRECT`
