### ISSUE TITLE
[Question] Can't open Paperlib

### ISSUE THREAD

**Issue by jianghao-zhang** [Future-Scholars/paperlib#393]
**Describe the bug**
Paperlib keeps loading and cannot be opened due to errors displaying "Failed to open cloud database" and "Failed to initialize the ...".

**Screenshots or Log**
<img width="859" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/81921082/8ce8ce71-87d8-4d17-bdf8-b3ae2245d585">

**System (please complete the following information):**
 - OS: macOS Version 14.3
 - Paperlib Version beta-electron-3.0.0-dev.11 and beta-electron-3.0.0-dev.10

**Comment by GeoffreyChen777** [comment]
Could you please share your log at here `~/Library/Logs/paperlib-beta`

**Comment by GeoffreyChen777** [comment]
Seems that you used a wrong cloud sync method.

Are you using the cloud database?

If yes, please open the config file at: `~/Library/Application\ Support/paperlib-beta/config.json`

Edit it:
<img width="323" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/7dc77d33-f6ba-4fe8-9444-6dd08287568a">

If your cloud database is partition-based, please set it to `false`. Otherwise, please set it to `true`.

Then reopen paperlib.

**Comment by GeoffreyChen777** [comment]
If you don't use cloud database, please set `"userSync": false`

**Comment by jianghao-zhang** [comment]
It's perfectly resolved. Thanks for your help!
