### ISSUE TITLE
[Question] No folder category option when editing the entry in 3.0 version

### ISSUE THREAD

**Issue by Raibows** [Future-Scholars/paperlib#402]
I categorized my papers by creating different folders in paperlib. 

In 3.0 version, I try to assign a newly imported paper a folder label but find there is no such option in the entry editing view. It seems like the only way for that is dragging this entry to a specific folder in the left side, which is not convenient especially for having a large number of folders and each paper belonging to multiple folders.

Actually, I can't distinguish the function between folders and tags, how to utilize these two categories? Do you have some suggestions?

If the tag category is recommended, I hope paperlib at least will provide a migration option for people like me converting already existed folders to tags. Thanks!

**Comment by GeoffreyChen777** [comment]
Hi, we removed the folder option in the editing view. The reason is that, in 3.0, we introduced the hierarchical folders. So it makes no sense to sign folders like tags.

Previously, we have two categorizers— tags and folders. But to be honest, they are quite similar.

But now, they are different.

Tags are atomic. So it cannot be hierarchical. Tags usually indicate the property of a paper, such as the topics of a paper.

Folders are more free to use. You can use it as tags. Or you can create many hierarchical folders to organize your papers, just like the folders in a file system.

**Comment by Raibows** [comment]
Hi! Thanks for your reply. 

I got it, the tags now are recommended to manage or categorize the papers. But just as you said, in the previous versions they are quite similar, so many people may use folders to categorize their papers. The introduced changes have less compatibility. And even if I still use folders instead of recommended tags, it's so inefficient for me to drag every paper since the folder option in the editing view has been removed. 

Thus, I hope we could have a migration option or could you introduce some tricks to finish the migration from folders to tags.

**Comment by GeoffreyChen777** [comment]
It depends on how many folders you have.

If you have less than 20. I think you can do:

- create tags according to your folders.
- click each folder, then select all papers in the list with pressing `shift`.
- drag all of them into corresponding tags.
- repeat the above operation for all folders.


If you have more than 20. I would suggest migrating them via an extension. Such as a command extension:

https://paperlib.app/cn/extension-doc/ext-types/command-ext.html

It's very easy to implement. just 10 lines of code should be enough.

If you don't know how to develop such an extension, I can help you. https://share.1password.com/s#bjj8Qhq8qGJOKCN_MtDXwV9Ng55WFmGuTCcfuJ15Lmw
