### ISSUE TITLE
[Feature Request] ollama support

### ISSUE THREAD

**Issue by mintisan** [Future-Scholars/paperlib#466]
Using the local large language model, ollama provides a service interface compatible with OpenAI, making it convenient for summarization, translation, and so on.

You can refer to this open-webui project.

- https://github.com/open-webui/open-webui
- https://github.com/ollama/ollama

**Comment by GeoffreyChen777** [comment]
If you wish to connect to local LLMs, you can implement your own extensions: https://paperlib.app/en/extension-doc/
or contribute to our official extension: https://github.com/Future-Scholars/paperlib-ai-summary-extension

I cannot do it. The reason is that my laptop is not powerful enough for local LLMs.

**Comment by mintisan** [comment]
ok, I will look how to do it, thanks.
